name: Daily Download
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  articles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx hdl -c articles
