name: Download Habbo Files
on:
 schedule:
    - cron: '0 */4 * * *'
 workflow_dispatch:
jobs:
 main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            token: ${{ secrets.GITHUB_COMMENT }}
      - uses:  actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm i

      # badges
      - name: Download Badges
        run: node src/index.js -c badges

      # clothes
      - name: Download Clothes
        run: node src/index.js -c clothes

      # effects
      - name: Download Effects
        run: node src/index.js -c effects

      # ficons
      - name: Download Furniture Icons
        run: node src/index.js -c ficons

      # gamedata
      - name: Download Gamedata Files
        run: node src/index.js -c gamedata

      # Echo current date and time to currentFile.js
      - name: Update currentFile.js with current date and time
        run: |
          echo "const currentDate = '$(date)';" > current.js

      # commit
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: resource
