name: Daily Download
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  icons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install packages
        run: npm i
      - name: Run habbo-downloader
        run: node src/index.js -c icons
      - name: Git status
        run: git status
