name: Daily Download
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  gamedata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Set current date as environment variable
        run: |
          echo "NOW=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
          echo "date test: $(NOW)"
      - name: Install packages
        run: npm i
      - name: Run habbo-downloader
        run: node src/index.js -c gamedata -o resource/test
      - name: Git status
        run: git status
      - name: Push changes
        run: |
          git config user.name higoka
          git config user.email nico.rickenbach@gmail.com
          git add resource
          git commit -m "daily resources download"
          git push origin dev
