name: Daily Download
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: node src/index.js -c badges
